### ISSUE TITLE
views + templates don't appear to co-locate

### ISSUE THREAD

**Issue by stefanpenner** [rwjblue/ember-module-migrator#18]

**Comment by rwjblue** [comment]
Thanks for reporting, should be easy to fix.

**Comment by rwjblue** [comment]
We will need to add some additional logic to templates outside of templates/components. I think currently it assumes they are all route templates. We need to make non component templates a separate type and ask the fileinfocollection if there is a route for that name, or if not if there's a view for it.

**Comment by rwjblue** [comment]
In #30 I added naive support for detecting "route views" vs non-route views. I defined a non-route view as any view that is invoked via `{{view "someLiteralString"` in a template, all others are "route views".

This certainly isn't perfect, but it is a start.
