### ISSUE TITLE
Begin fleshing out "pods support".

### ISSUE THREAD

**Issue by rwjblue** [rwjblue/ember-module-migrator#3]
The main thing that needs to be built out is the `buildFor` implementation that is found [here](https://github.com/rwjblue/ember-module-migrator/blob/master/lib/engines/classic/index.js#L13-L74).  We need to deconstruct a given path into the various parts (`collectionGroup`, `collection`, `namespace`, `name`, `type`, etc).  

It is quite possible that the actual type specific `FileInfo` implementations in [lib/engines/classic](https://github.com/rwjblue/ember-module-migrator/tree/master/lib/engines/classic) can actually be reused from the `buildFor` that we create for `pods`.  If that ends up being possible, we should move those general purpose `FileInfo` objects into `lib/models` instead.

A great start would be a WIP PR adding acceptance tests like the `input.js` and `output.js` files in [test/fixtures/classic-acceptance](https://github.com/rwjblue/ember-module-migrator/tree/master/test/fixtures/classic-acceptance).

**Comment by rwjblue** [comment]
@trabus - Do you know of any OSS projects using pods that we can test on?

**Comment by trabus** [comment]
I am not aware of any, other than maybe ember-jobs, but that one was a bit experimental from what I recall.

I started work on this but haven't pushed anything yet. Trying to get an understanding of the whole process as I go.

**Comment by rwjblue** [comment]
Someone mentioned to me that the HospitalRun frontend is an OSS pods app: https://github.com/HospitalRun/hospitalrun-frontend.

**Comment by Turbo87** [comment]
https://github.com/aptible/dashboard.aptible.com is also using (a lot of) pods

**Comment by rwjblue** [comment]
I fleshed out the description section of this issue, would love help if someone wants to try and tackle it...

**Comment by trabus** [comment]
I might be able to find a few cycles to pick this back up this week. Day job has been bogarting all of my time. :\

**Comment by courajs** [comment]
How were you thinking apps with mixed usage would make use of these engines? Add a third HybridEngine to compose them? Or run them one at a time?

**Comment by NullVoxPopuli** [comment]
> @trabus - Do you know of any OSS projects using pods that we can test on?
https://gitlab.com/precognition-llc/aeonvera-ui
:-)

Hybrid traditional and pods, cause too many components. :-)

**Comment by rwjblue** [comment]
🎉
