### ISSUE TITLE
Repair import paths in moved files

### ISSUE THREAD

**Issue by mixonic** [rwjblue/ember-module-migrator#42]
When a file is migrated other files that `import` it may need to be corrected to use the now-changed module path.

Some WIP https://github.com/201-created/ember-module-migrator/commits/import-test

**Comment by andyhot** [comment]
Just took a look at the WIP and shouldn't the expectation for `application.js` in `class-relative-imports` be
```
import NestedUtil from "my-app/src/utils/nested/util"; import SingleUtil from "my-app/src/utils/single";
```
instead of
```
import NestedUtil from "my-app/src/ui/utils/nested/util"; import SingleUtil from "my-app/src/ui/utils/single";
```
?
