### ISSUE TITLE
Rewrite imports to /config files

### ISSUE THREAD

**Issue by andyhot** [rwjblue/ember-module-migrator#48]
There's always at least one such import:

- `app/app.js` which includes `import config from "./config/environment` and which will have to become `import config from "../config/environment` )

**Comment by andyhot** [comment]
I've created some test-fixtures for this over at https://github.com/andyhot/ember-module-migrator/commit/5adf76c3b1226b2b890369b2f4993036dfd7abd2

**Comment by rwjblue** [comment]
Fixture looks good.

**Comment by andyhot** [comment]
Thx!
Fyi, I have the code working at https://github.com/rwjblue/ember-module-migrator/compare/master...andyhot:feature/config-imports?expand=1 but I want to clean it up a bit before it becomes a PR

**Comment by mixonic** [comment]
@andyhot just ran into this converting travis 👍

**Comment by rwjblue** [comment]
resolved by #49
