### ISSUE TITLE
non standard test file renamed oddly

### ISSUE THREAD

**Issue by efx** [rwjblue/ember-module-migrator#63]
Following the readme steps for an ember application I work on, I noticed one test file had an unusual name and path. Using ember-cli@2.15.1, node 8.5.
# expectation
I expected this particular file to have a shorter path and filename.
# result
Original file path:
`tests/integration/worker-export-test.js`
Migrated path:
`src/worker-export-test.js/worker-export/worker-export-test.j-integration-test.js`

**Comment by rwjblue** [comment]
Yikes. Ya, so the reason this happens is that we are assuming the first path segment after `tests/integration` is the type (which is the more common setup). We can fix this by opting out of migration if the type isn’t in a known set of valid types.

**Comment by efx** [comment]
Ah, thanks for the explanation. If I get some "free" time in the next few days, I'll take a stab at a PR for this.

**Comment by efx** [comment]
I'm closing as I think it is an acceptable workaround to just move the test file into `tests/integration/components/worker-export-test`.
